export const REQUEST_USER = 'REQUEST_USER';
export const RECEIVE_USER = 'RECEIVE_USER';
export const SET_LOGIN_USER = 'SET_LOGIN_USER';

export const SET_ADMIN_MODE = 'SET_ADMIN_MODE';

export const SET_CURRENT_ORGANIZATION = 'SET_CURRENT_ORGANIZATION';
export const SET_ORGANIZATIONS_COLLABORATOR = 'SET_ORGANIZATIONS_COLLABORATOR';
export const SET_ORGANIZATIONS_OWNED = 'SET_ORGANIZATIONS_OWNED';

export const SET_ORGANIZATION_COLLABORATORS = 'SET_ORGANIZATION_COLLABORATORS';
export const SET_ORGANIZATION_OWNER = 'SET_ORGANIZATION_OWNER';
export const SET_ORGANIZATION_ROLES = 'SET_ORGANIZATION_ROLES';

export const SET_ORGANIZATION_PROJECTS = 'SET_ORGANIZATION_PROJECTS';
export const ADD_ORGANIZATION_PROJECT = 'ADD_ORGANIZATION_PROJECT';
export const REMOVE_ORGANIZATION_PROJECT = 'REMOVE_ORGANIZATION_PROJECT';
