export const REQUEST_USER = 'REQUEST_USER';
export const RECEIVE_USER = 'RECEIVE_USER';
export const SET_LOGIN_USER = 'SET_LOGIN_USER';

export const SET_CURRENT_ORGANIZATION = 'SET_CURRENT_ORGANIZATION';
export const SET_ORGANIZATIONS = 'SET_ORGANIZATIONS';

export const SET_ORGANIZATION_COLLABORATORS = 'SET_ORGANIZATION_COLLABORATORS';
export const SET_ORGANIZATION_OWNER = 'SET_ORGANIZATION_OWNER';

export const SET_ADMIN_MODE = 'SET_ADMIN_MODE';
