name: Deploy PFE Lab to Production

on:
    # Run this workflow on push to production-release tag (via chatops)
    push:
        tags:
          - production-release

    # Allow running this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_STATIC_SITES }}

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: npm install
    - run: npm run _build-production

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        creds: ${{ secrets.AZURE_STATIC_SITES }}
        inlineScript: |
            az storage blob upload-batch --account-name zooniversestatic -d '$web/lab.zooniverse.org' -s ./dist

# Azure logout
    - name: logout
      run: |
            az logout
