name: Run PFE Lab Tests

on:
    # Run this workflow on creation (or sync to source branch) of a new pull request
    pull_request:

    # Allow running this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Reconfigure git to use HTTPS protocol
      run: >
        git config --global url."https://github.com/".insteadOf
        ssh://git@github.com/

    - name: Node.js build
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/hydrogen'
        cache: 'npm'

    - run: npm ci
    - run: npm test
    
